//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanciaRed.Model.Model_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditApplications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CreditApplications()
        {
            this.Credits = new HashSet<Credits>();
            this.CreditApplications_Policies = new HashSet<CreditApplications_Policies>();
        }
    
        public int IdCreditApplication { get; set; }
        public System.DateTime DateApplication { get; set; }
        public Nullable<System.DateTime> DateAcepted { get; set; }
        public int AmountTotal { get; set; }
        public byte[] ProofAddress { get; set; }
        public byte[] ProofINE { get; set; }
        public byte[] ProofLastPayStub { get; set; }
        public int IdEmployeeApplication { get; set; }
        public int IdStatusCreditApplication { get; set; }
        public int IdPromotion { get; set; }
        public int IdClient { get; set; }
        public string ValorationOpinion { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credits> Credits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditApplications_Policies> CreditApplications_Policies { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Promotions Promotions { get; set; }
        public virtual StatusesCreditApplication StatusesCreditApplication { get; set; }
    }
}
