//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanciaRed.Model.Model_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditApplications_Policies
    {
        public int IdCreditApplication_Policy { get; set; }
        public int IdCreditApplication { get; set; }
        public int IdPolicy { get; set; }
    
        public virtual CreditApplications CreditApplications { get; set; }
        public virtual Policies Policies { get; set; }
    }
}
