//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanciaRed.Model.Model_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credits
    {
        public int IdCredit { get; set; }
        public Nullable<int> AmountLeft { get; set; }
        public int IdStatusCredit { get; set; }
        public byte[] SignedDocument { get; set; }
        public byte[] PaymentLayout { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public int IdCreditApplication { get; set; }
    
        public virtual CreditApplications CreditApplications { get; set; }
        public virtual StatusesCredit StatusesCredit { get; set; }
    }
}
